### ISSUE TITLE
GTDemo 3.1 启动失败

### ISSUE THREAD

**Issue by glumes** [Tencent/GT#29]
GT 3.1 Demo 安装后启动崩溃。

FATAL EXCEPTION: main
                                                                 Process: com.gtr.sdkdemo, PID: 15551
                                                                 android.util.SuperNotCalledException: Activity {com.gtr.sdkdemo/com.gtr.test.MainActivity} did not call through to super.onCreate()
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

提示没有调用 super.onCreate() ，显然是调用了的。

Hook 失败的点：

 findAndBackupAndHook ,targetMethod = 0
03-07 08:24:38.016 15760-15760/com.gtr.sdkdemo E/YAHFA-Native: Cannot find target method onAttach(Landroid/content/Context;)V
03-07 08:24:38.017 15760-15760/com.gtr.sdkdemo D/YHOOK: target method param count is 1
03-07 08:24:38.017 15760-15760/com.gtr.sdkdemo D/YAHFA-Native: findAndBackupAndHook

 Start findAndBackupAndHook for method performDetach()V
03-07 08:24:38.029 15760-15760/com.gtr.sdkdemo D/YAHFA-Native: findAndBackupAndHook ,targetMethod = 0
03-07 08:24:38.030 15760-15760/com.gtr.sdkdemo E/YAHFA-Native: Cannot find target method performDetach()V
03-07 08:24:38.031 15760-15760/com.gtr.sdkdemo D/YHOOK: target method param count is 0
03-07 08:24:38.035 15760-15760/com.gtr.sdkdemo D/YAHFA-Native: findAndBackupAndHook

**Comment by brianxcli** [comment]
Hi, 请问您使用的机型和系统版本？

**Comment by glumes** [comment]
用的是海思的平台，系统是 5.1的

**Comment by brianxcli** [comment]
您工程里build.gradle文件如何定义的eabi？ 目前Sdk支持v7a, 64 v8a跟x86

**Comment by crazygj** [comment]
小白遇到了同样的问题。。用的机器是魅族MX6 ,系统Android 6.0的
shell@MX6:/proc $ cat cpuinfo
Processor	: AArch64 Processor rev 4 (aarch64)

就是把GTDemo导入之后什么也没改然后运行报错，不知道怎么解决。。

**Comment by llliuyx** [comment]
相同的问题，华为荣耀畅玩5x，Android 6.0，同样是什么都没改，有解决的吗？

**Comment by llliuyx** [comment]
@brianxcli 
https://github.com/llliuyx/GTLearn/blob/master/GTDemoLaunchCrash.log

**Comment by bai991003885** [comment]
@brianxcli 项目里面的so库是armabi，集成GT SDK后大部分8.0以下机器闪退，和这个有关系吗
