### ISSUE TITLE
在application initsdk  大部分手机有空指针错误

### ISSUE THREAD

**Issue by bai991003885** [Tencent/GT#41]
用的是最新的sdk和jar,用的是直接compile的方式，在appliction的时候init
一加5运行正常，但是其他手机试了小米 华为 三星（8.0以下）都闪退了，而且都是这个错误
日志如下： 
java.lang.RuntimeException: Unable to create application com.quvideo.xiaoying.DebugApplicationBase: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4903)
        at android.app.ActivityThread.access$1500(ActivityThread.java:182)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5682)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
        at com.tencent.wstt.gt.collector.monitor.yhook.DBHookList.openDatabase(DBHookList.java:133)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1280)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at com.pingstart.adsdk.c.a.j(SourceFile:110)
        at com.pingstart.adsdk.inner.model.a.a.m(SourceFile:24)
        at com.pingstart.adsdk.inner.model.a.e.m(SourceFile:9)
        at com.pingstart.adsdk.i.n.A(SourceFile:23)
        at com.pingstart.adsdk.PingStartSDK.initializeSdk(SourceFile:50)
        at com.pingstart.adsdk.PingStartSDK.initializeSdk(SourceFile:37)
        at com.quvideo.xiaoying.ads.pingstart.PingStartSdkMgr.initSdk(PingStartSdkMgr.java:31)
        at com.quvideo.xiaoying.ads.AbsAdGlobalMgr$1.onInitSdk(AbsAdGlobalMgr.java:30)
        at com.quvideo.xiaoying.ads.AbsAdGlobalMgr$1.onInitSdk(AbsAdGlobalMgr.java:28)
        at com.quvideo.xiaoying.ads.AbsAdGlobalMgr.initAdsSdk(AbsAdGlobalMgr.java:73)
        at com.quvideo.xiaoying.ads.AbsAdGlobalMgr.initSdkInApplication(AbsAdGlobalMgr.java:28)
        at com.quvideo.xiaoying.app.ApplicationBaseFlavor.initAdsSDK(ApplicationBaseFlavor.java:15)

我导入sdk的源码看，dbhookList类的133行代码进去就是返回空指针。而且看不到调用这个函数的地方，这个函数是so库里面调用的吗？

**Comment by svengong** [comment]
hook失败了，原因单从这个日志看不清。
