### ISSUE TITLE
AUT界面频繁点击会出现ANR

### ISSUE THREAD

**Issue by liion631818** [Tencent/GT#45]

**Comment by brianxcli** [comment]
可以给出详细一点的描述么

**Comment by liion631818** [comment]
一直点击AUT frament就会出现，我们的设备性能不是很好，我没在手机上试过。

> 06-22 16:32:04.117 2370-2500/? E/ActivityManager: ANR in com.tencent.wstt.gt (com.tencent.wstt.gt/.activity.GTMainActivity)
                                                  PID: 8588
                                                  Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 11.  Wait queue head age: 7019.0ms.)
                                                  Load: 7.09 / 6.08 / 5.89
                                                  CPU usage from 60ms to -10556ms ago:
                                                    56% 2370/system_server: 25% user + 30% kernel / faults: 8598 minor 277 major
                                                    50% 8588/com.tencent.wstt.gt: 25% user + 25% kernel / faults: 56012 minor 53 major
                                                    10% 23427/com.tencent.android.qqdownloader:daemon: 4.9% user + 5.2% kernel / faults: 2445 minor 26 major
                                                    9.7% 259/logd: 8.4% user + 1.3% kernel / faults: 28 minor
                                                    8.9% 3869/com.android.phone: 3.7% user + 5.1% kernel / faults: 3162 minor 114 major
                                                    0% 768/debuggerd_real: 0% user + 0% kernel / faults: 4132 minor 72 major
                                                    7.4% 3137/com.android.systemui: 4.1% user + 3.2% kernel / faults: 2625 minor 71 major
                                                    4.3% 16227/com.kingroot.kinguser:service: 2.8% user + 1.5% kernel / faults: 12203 minor 5 major
                                                    3% 171/mmcqd/0: 0% user + 3% kernel
                                                    1% 3577/com.quicinc.cne.CNEService: 0.4% user + 0.5% kernel / faults: 1775 minor 259 major
                                                    2.4% 296/paxservice: 0.5% user + 1.8% kernel / faults: 1 minor
                                                    0% 3678/com.pax.logcat: 0% user + 0% kernel / faults: 1950 minor 277 major
                                                    1.8% 1//init: 0% user + 1.8% kernel
                                                    1.7% 25410/kworker/0:0: 0% user + 1.7% kernel
                                                    1.1% 3746/com.pax.networkmanager: 0.5% user + 0.5% kernel / faults: 1405 minor 34 major
                                                    0% 3770/com.pax.otaupdate: 0% user + 0% kernel / faults: 1624 minor 57 major
                                                    0% 3064/com.paxdroid.osmanager: 0% user + 0% kernel / faults: 1592 minor 219 major
                                                    0.6% 3297/com.pax.smartcardmanager: 0.4% user + 0.1% kernel / faults: 1332 minor 59 major
                                                    0% 3712/com.qualcomm.qti.imstestrunner: 0% user + 0% kernel / faults: 1677 minor 203 major
                                                    0% 3794/com.qualcomm.qti.gesture: 0% user + 0% kernel / faults: 1640 minor 252 major
                                                    0% 3818/com.paxdroid.verify: 0% user + 0% kernel / faults: 1535 minor 167 major
                                                    0% 3893/com.pax.paxbtprinter: 0% user + 0% kernel / faults: 1666 minor 214 major
                                                    1.4% 373/adbd: 0.3% user + 1% kernel
                                                    0% 3843/com.pax.batteryconsumption: 0% user + 0% kernel / faults: 1527 minor 174 major
                                                    0.9% 124/hwrng: 0% user + 0.9% kernel
                                                    0.9% 17718/com.tencent.android.qqdownloader: 0.6% user + 0.2% kernel / faults: 815 minor 13 major
                                                    0.9% 23114/kworker/0:2: 0% user + 0.9% kernel
                                                    0.8% 95/kswapd0: 0% user + 0.8% kernel
                                                    0.8% 22728/logcat: 0.1% user + 0.6% kernel
                                                    0.8% 25369/kworker/u8:2: 0% user + 0.8% kernel
                                                    0.7% 33/kworker/u9:0: 0% user + 0.7% kernel
                                                    0.6% 266/surfaceflinger: 0.1% user + 0.4% kernel / faults: 13 minor 1 major
                                                    0.5% 5837/com.tencent.android.qqdownloader:wns: 0.1% user + 0.3% kernel / faults: 324 minor 5 major
                                                    0.5% 10014/kworker/u8:5: 0% user + 0.5% kernel
                                                    0.5% 24389/kworker/u8:1: 0% user + 0.5% kernel
                                                    0% 25397/kworker/3:0: 0% user + 0% kernel
                                                    0.4% 12028/logcat: 0.2% user + 0.1% kernel
                                                    0.3% 12/ksoftirqd/1: 0% user + 0.3% kernel
                                                    0.3% 20/ksoftirqd/3: 0% user + 0.3% kernel
                                                    0.3% 219/jbd2/mmcblk0p40: 0% user + 0.3% kernel
                                                    0.1% 933/paxdroid_logservice: 0% user + 0.1% kernel / faults: 158 minor
                                                    0.1% 935/pax_logcat: 0% user + 0% kernel
                                                    0.3% 22983/kworker/1:4: 0% user + 0.3% kernel
                                                    0.2% 3/ksoftirqd/0: 0% user + 0.2% kernel
                                                    0.2% 16/ksoftirqd/2: 0% user + 0.2% kernel
                                                    0.1% 14195/com.tencent.android.qqdownloader:connect: 0% user + 0% kernel / faults: 838 minor 7 major
                                                    0.1% 25128/kworker/2:0: 0% user + 0.1% kernel
                                                    0.1% 7/rcu_preempt: 0% user + 0.1% kernel
                                                    0.1% 262/lmkd: 0% user + 0.1% kernel / faults: 8 minor
                                                    0.1% 349/sdcard: 0% user + 0.1% kernel / faults: 6 minor
                                                    0.1% 640/kuInotify: 0.1% user + 0% kernel / faults: 2 minor
                                                    0% 6/kworker/u8:0: 0% user + 0% kernel
                                                    0% 29/kworker/0:1H: 0% user + 0% kernel
                                                    0% 163/cfinteractive: 0% user + 0% kernel
                                                    0% 165/irq/253-7864900: 0% user + 0% kernel
                                                    0% 263/servicemanager: 0% user + 0% kernel
                                                    0% 380/kworker/3:1H: 0% user + 0% kernel
                                                    0% 519/ku.sud: 0% user + 0% kernel / faults: 9
06-22 16:32:04.130 8588-8588/? I/System.out: change tab time:1
06-22 16:32:04.142 2370-2500/? W/ActivityManager:   Force finishing activity 1 com.tencent.wstt.gt/.activity.GTMainActivity
06-22 16:32:04.155 2370-27371/? E/ActivityManager: Error reading /data/anr/traces.txt
                                                   java.io.FileNotFoundException: /data/anr/traces.txt: open failed: ENOENT (No such file or directory)
                                                       at libcore.io.IoBridge.open(IoBridge.java:456)
                                                       at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                       at android.os.FileUtils.readTextFile(FileUtils.java:227)
                                                       at com.android.server.am.ActivityManagerService$20.run(ActivityManagerService.java:12105)
                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                       at libcore.io.Posix.open(Native Method)
                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                       at libcore.io.IoBridge.open(IoBridge.java:442)
                                                       at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                       at android.os.FileUtils.readTextFile(FileUtils.java:227) 
                                                       at com.android.server.am.ActivityManagerService$20.run(ActivityManagerService.java:12105) 
06-22 16:32:04.178 8588-8588/? I/System.out: change tab time:45
